version: 0.0
os: linux
files:
- source: src
  destination: /var/www/html

# permissions:
#   - object: /opt/tomcat/bin
#     pattern: "*.sh"
#     owner: root
#     group: root
#     mode: 755
#     type:
#       - file

hooks:
  ApplicationStop:
  - location: script/suspend-scaling.sh
    timeout: 60
    runas: root

  - location: script/stop-service.sh
    timeout: 180
    runas: root

  BeforeInstall:
  - location: script/earse-application.sh
    timeout: 60
    runas: root

  ApplicationStart:
  - location: script/start-service.sh
    timeout: 180
    runas: root

  ValidateService:
  - location: script/verify-service.sh
    timeout: 60
    runas: root

  - location: script/resume-scaling.sh
    timeout: 60
    runas: root
